### ISSUE TITLE
change default directory _site

### ISSUE THREAD

**Issue by fromthestone** [kimfucious/kbj#14]
Hi,
I am using your theme, and I changed `_site` folder inside `gulpfile.js` and inside `_assets/gulp_config/path.js.`
but when I do `yarn serve`, always doing:
`Destination: /Volumes/SSD2/sakura/_site`
instead of
`Destination: /Volumes/SSD2/sakura/other_folder`
What else it needs to change?

**Comment by kimfucious** [comment]
Hi @fromthestone 

Sorry for the late response, I haven't been looking at this project for a while.

Have a look at the paths.js file in the `_assets/gulp_config/` directory and check the `Directories` section.

There you will find:

```js
// Directories
paths.assetsDir = "_assets/"; // The files Gulp will handle.
paths.jekyllDir = ""; // The files Jekyll will handle.
paths.jekyllAssetsDir = "assets/"; // The asset files Jekyll will handle.
paths.nodeSrcDir = "node_modules/"; // Node source files.
paths.siteDir = "_site/"; // The resulting static site.
paths.siteAssetsDir = "_site/assets/"; // The resulting static site's assets.
```
I'm not sure exactly what you're trying to do, but that should help.

Best,

Kim
